'use strict';
const fs   = require('fs');
const path = require('path');

const REPO_ROOT    = path.join(__dirname, '..');
const SKILLS_DIR   = path.join(REPO_ROOT, 'skills');
const REGISTRY_OUT = path.join(REPO_ROOT, 'skill_registry.json');
const SKILLS_MD    = path.join(SKILLS_DIR, 'skills', 'SKILL.md');

/**
 * Parse YAML-style frontmatter from a SKILL.md file.
 * Only extracts: name, description, version.
 */
function parseFrontmatter(content) {
    const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
    if (!match) return {};
    const fm = {};
    for (const line of match[1].split('\n')) {
        const [key, ...rest] = line.split(':');
        if (key && rest.length) fm[key.trim()] = rest.join(':').trim();
    }
    return fm;
}

/**
 * Rebuild skill_registry.json and skills/skills/SKILL.md.
 * Called at install time and via `npm run skills`.
 */
function rebuild() {
    if (!fs.existsSync(SKILLS_DIR)) {
        console.warn('skills/ directory not found — skipping registry build');
        return [];
    }

    const skills = [];

    for (const name of fs.readdirSync(SKILLS_DIR).sort()) {
        if (name === 'skills') continue; // skip self
        const mdPath = path.join(SKILLS_DIR, name, 'SKILL.md');
        if (!fs.existsSync(mdPath)) continue;

        const content = fs.readFileSync(mdPath, 'utf8');
        const fm = parseFrontmatter(content);

        skills.push({
            name:        fm.name        || name,
            description: fm.description || '',
            version:     fm.version     || '0.0.0',
            path:        `skills/${name}/SKILL.md`,
        });
    }

    // Write machine-readable registry
    fs.writeFileSync(REGISTRY_OUT, JSON.stringify(skills, null, 2) + '\n');

    // Write /skills slash command
    fs.mkdirSync(path.dirname(SKILLS_MD), { recursive: true });
    const lines = [
        '---',
        'name: skills',
        'description: List all available MinusWorkflows skills with descriptions',
        'version: 1.0.0',
        '---',
        '',
        '# MinusWorkflows — Available Skills',
        '',
        'Invoke any skill with `/<name>` in Claude Code or `Gemini, <name>: [goal]` in Gemini CLI.',
        '',
        ...skills.map(s => `- **/${s.name}** (v${s.version}) — ${s.description}`),
        '',
        `_Auto-generated by skill_registry.js — ${new Date().toISOString()}_`,
    ];
    fs.writeFileSync(SKILLS_MD, lines.join('\n') + '\n');

    console.log(`  skill_registry.js: ${skills.length} skills indexed → skill_registry.json + /skills command`);
    return skills;
}

module.exports = { rebuild, parseFrontmatter };

// Run directly: node utils/skill_registry.js
if (require.main === module) rebuild();
