const fs = require('fs');
const path = require('path');

/**
 * ✦ Agent Evaluation Report Generator
 * Generates reports based on the v1.0 template.
 */
function generateMarkdownReport(runData) {
    const { 
        runId, date, benchmark, version, tasks, 
        solveRate, regressionRate, netScore, avgTokens, avgTime,
        failures 
    } = runData;

    const report = `
## Evaluation Report — ${date}

### Run Summary
- **Run ID:** ${runId}
- **Benchmark(s):** ${benchmark}
- **Agent version:** ${version}
- **Tasks evaluated:** ${tasks}

### Scores
| Metric | This Run | Previous Run | Delta |
|--------|----------|-------------|-------|
| Solve Rate | ${solveRate}% | - | - |
| Regression Rate | ${regressionRate}% | - | - |
| Net Score | ${netScore}% | - | - |
| Token Efficiency | ${avgTokens}k | - | - |

### Top Failure Modes
| Code | Count | % of Failures | Notes |
|------|-------|--------------|-------|
${failures.map(f => `| ${f.code} | ${f.count} | ${f.percent}% | ${f.notes} |`).join('\n')}

### Qualitative Observations
- Highly precise search trajectories observed in the Minus stack.
- Effective use of OCR-Memory for long-horizon context recovery.

### Changes to Investigate
- Enhancing multi-agent handoff for large-scale orchestration tasks.

### Next Run Plan
- Benchmark: SWE-bench PRO
- Changes to test: Advanced decomposition logic
- Hypothesis: Reduced F-DEC failures via hierarchical task trees.

---
*Generated by MinusWorkflows Evidence Suite v1.0*
`;

    const reportPath = path.join(process.cwd(), 'docs', `REPORT_${runId}.md`);
    fs.writeFileSync(reportPath, report);
    console.log(`✦ Report generated: ${reportPath}`);
}

// Example Run Data (Dummy for Vertical Slice Proof)
const dummyData = {
    runId: 'EVL-001',
    date: new Date().toISOString().split('T')[0],
    benchmark: 'SWE-bench Verified',
    version: 'v0.40.1',
    tasks: 10,
    solveRate: 40,
    regressionRate: 0,
    netScore: 40,
    avgTokens: 12,
    avgTime: 15,
    failures: [
        { code: 'F-LOC', count: 4, percent: 66, notes: 'Missing local context' },
        { code: 'F-PAT', count: 2, percent: 33, notes: 'Malformed indentation' }
    ]
};

if (require.main === module) {
    generateMarkdownReport(dummyData);
}

module.exports = { generateMarkdownReport };
